@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "app.controllers.ProductoController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1379517809 { 
   	label=archivosjson
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ProductosJSON580725052[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ProductosJSON</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ cargar(archivo: String): List&lt;Producto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ guardar(productos: List&lt;Producto&gt;, archivo: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1659632566 { 
   	label=objetos
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ListaProductos1883495805[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListaProductos</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   productos: LinkedList&lt;Producto&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   urlJson: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ actualizarProducto(productoActualizado: Producto)</TD></TR>
<TR><TD ALIGN="LEFT" >+ agregarProducto(producto: Producto)</TD></TR>
<TR><TD ALIGN="LEFT" >+ buscarProducto(idProducto: int): Producto</TD></TR>
<TR><TD ALIGN="LEFT" >+ eliminarProducto(producto: Producto)</TD></TR>
<TR><TD ALIGN="LEFT" >+ generarNuevoId(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ procesarImagen(imagen: MultipartFile): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Producto1883495805[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Producto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cantidadDisponible: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   categoria: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   descripcion: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   imagenUrl: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nombreProducto: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   precio: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   proveedorUsuario: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1714548649 { 
   	label=controllers
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ProductoController842536970[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ProductoController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   listaProductos: ListaProductos [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ actualizarProducto(id: int, nombreProducto: String, categoria: String, descripcion: String, precio: float, cantidadDisponible: Integer, proveedorUsuario: String, imagen: MultipartFile): ResponseEntity&lt;Producto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ crearProducto(productoJson: String, imagen: MultipartFile): ResponseEntity&lt;Producto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ eliminarProducto(id: int): ResponseEntity&lt;Void&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getProductoById(id: int): ResponseEntity&lt;Producto&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
ListaProductos1883495805 -> Producto1883495805[label="productos
[0..*]"];
ProductoController842536970 -> ListaProductos1883495805[label="listaProductos
[0..1]"];
    
}
@enduml